CREATE TABLE TB_VEICULOS (
    VEI_ID SERIAL PRIMARY KEY,
    VEI_MARCA VARCHAR(30) NOT NULL,
    VEI_NOME VARCHAR(50) NOT NULL,
    VEI_TIPO INT NOT NULL,
    VEI_COR VARCHAR(50) NOT NULL,
    VEI_QTDLUGARES INT NOT NULL,
    VEI_CAMBIO VARCHAR(30) NOT NULL,
    VEI_BANCOCOURO INT NOT NULL,
    VEI_ARCOND INT NOT NULL,
    VEI_DIRECAOHIDRAU INT NOT NULL,
    VEI_VIDROELEC INT NOT NULL,
    VEI_SENSORRE INT NOT NULL,
    VEI_CAMERARE INT NOT NULL,
    VEI_DISPONIVEL INT NOT NULL,
    VEI_PLACA VARCHAR(6) NOT NULL UNIQUE,
    VEI_CILINDRADAS INT,
    VEI_PRECODIARIA DECIMAL(10,2) NOT NULL
);

CREATE TABLE TB_TIPO_VEICULO(
    TVI_ID SERIAL PRIMARY KEY,
    TVI_NOMETIPO VARCHAR(20) NOT NULL
);

CREATE TABLE TB_PESSOA(
    PES_ID SERIAL PRIMARY KEY,
    PES_NOME VARCHAR(100) NOT NULL,
    PES_NRODOC VARCHAR(14) NOT NULL UNIQUE,
    PES_NROCNH VARCHAR(10) NOT NULL UNIQUE,
    PES_DATANASC DATE,
    PES_EDEID INT NOT NULL,
    PES_TELEFONE VARCHAR(20),
    PES_EMAIL VARCHAR(100),
    PES_DATACAD DATE NOT NULL
);

CREATE TABLE TB_ENDERECO_PESSOA(
    EDE_ID SERIAL PRIMARY KEY,
    EDE_NOMERUA VARCHAR(100) NOT NULL,
    EDE_NRO INT NOT NULL,
    EDE_COMPLEMENTO VARCHAR(50),
    EDE_CEP VARCHAR(9) NOT NULL,
    EDE_MUNID INT NOT NULL
);

CREATE TABLE TB_MUNICIPIO(
    MUN_ID SERIAL PRIMARY KEY,
    MUN_NOME VARCHAR(100) NOT NULL,
    MUN_EFE INT NOT NULL
);

CREATE TABLE TB_ESTADO_FEDERACAO(
    EFE_ID SERIAL PRIMARY KEY,
    EFE_NOME VARCHAR(50) NOT NULL,
    EFE_UF CHAR(2) NOT NULL,
    EFE_PAIS VARCHAR(50) NOT NULL
);

CREATE TABLE TB_PRODUTOS(
    PRO_ID SERIAL PRIMARY KEY,
    PRO_NOME VARCHAR(100) NOT NULL,
    PRO_DESC VARCHAR(255),
    PRO_PRECO DECIMAL(10, 2) NOT NULL,
    PRO_QTDDISPONIVEL INT DEFAULT 0
);

CREATE TABLE TB_LOCACOES(
    LOC_ID SERIAL PRIMARY KEY,
    LOC_PESID INT NOT NULL,
    LOC_VEIID INT NOT NULL,
    LOC_DATAINI DATE NOT NULL,
    LOC_DATAFIN DATE,
    LOC_DIASLOCADOS INT NOT NULL DEFAULT 0,
    LOC_TOTALBRUTO DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    LOC_TOTALLIQUIDO DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE TB_PRODUTOS_LOCADOS(
    PLO_ID SERIAL PRIMARY KEY,
    PLO_PROID INT NOT NULL,
    PLO_LOCID INT NOT NULL
);

CREATE TABLE TB_DESCONTOS_ACRESCIMOS(
    DAC_ID SERIAL PRIMARY KEY,
    DAC_NOME VARCHAR(20) NOT NULL,
    DAC_DESCRICAO VARCHAR(100),
    DAC_VALORDESACR DECIMAL(10,2) NOT NULL
);

CREATE TABLE TB_JUROS_MULTA(
    JMU_ID SERIAL PRIMARY KEY,
    JMU_NOME VARCHAR(20) NOT NULL,
    JMU_DESCRICAO VARCHAR(100),
    JMU_PORCENTAGEM DECIMAL(1,4) NOT NULL
);

CREATE TABLE TB_MULTA_LOCACOES(
    MLO_ID SERIAL PRIMARY KEY,
    MLO_LOCID INT NOT NULL,
    MLO_JMUID INT NOT NULL
);

CREATE TABLE TB_DESACR(
    DLO_ID SERIAL PRIMARY KEY,
    DLO_LOCID INT NOT NULL,
    DLO_DACID INT NOT NULL
);

CREATE TABLE TB_LOCACOES_PAG(
    LPA_ID SERIAL PRIMARY KEY,
    LPA_LOCID INT NOT NULL,
    LPA_SITPAG VARCHAR(20) NOT NULL,
    LPA_VALORPAGO DECIMAL(10,2) NOT NULL DEFAULT 0.00
);



























