ALTER TABLE TB_VEICULOS ADD CONSTRAINT fk_veiculos_tipoveiculo
FOREIGN KEY (VEI_TIPO) REFERENCES TB_TIPO_VEICULO(TVI_ID);

ALTER TABLE TB_PESSOA ADD CONSTRAINT fk_pessoa_endereco
FOREIGN KEY (PES_EDEID) REFERENCES TB_ENDERECO_PESSOA(EDE_ID);

ALTER TABLE TB_ENDERECO_PESSOA ADD CONSTRAINT fk_endereco_cidade
FOREIGN KEY (EDE_MUNID) REFERENCES TB_MUNICIPIO(MUN_ID);

ALTER TABLE TB_MUNICIPIO ADD CONSTRAINT fk_cidade_estado
FOREIGN KEY (MUN_EFE) REFERENCES TB_ESTADO_FEDERACAO(EFE_ID);

ALTER TABLE TB_LOCACOES ADD CONSTRAINT fk_locacoes_pessoa
FOREIGN KEY (LOC_PESID) REFERENCES TB_PESSOA(PES_ID);

ALTER TABLE TB_LOCACOES ADD CONSTRAINT fk_locacoes_veiculos
FOREIGN KEY (LOC_VEIID) REFERENCES TB_VEICULOS(VEI_ID);

ALTER TABLE TB_PRODUTOS_LOCADOS ADD CONSTRAINT fk_produtoslocados_produtos
FOREIGN KEY (PLO_PROID) REFERENCES TB_PRODUTOS(PRO_ID);

ALTER TABLE TB_PRODUTOS_LOCADOS ADD CONSTRAINT fk_produtoslocados_locacoes
FOREIGN KEY (PLO_LOCID) REFERENCES TB_LOCACOES(LOC_ID);

ALTER TABLE TB_MULTA_LOCACOES ADD CONSTRAINT fk_multa_locacoes
FOREIGN KEY (MLO_LOCID) REFERENCES TB_LOCACOES(LOC_ID);

ALTER TABLE TB_MULTA_LOCACOES ADD CONSTRAINT fk_multa_jurosmulta
FOREIGN KEY (MLO_JMUID) REFERENCES TB_JUROS_MULTA(JMU_ID);

ALTER TABLE TB_DESACR ADD CONSTRAINT fk_descontoacrescimo_locacoes
FOREIGN KEY (DLO_LOCID) REFERENCES TB_LOCACOES(LOC_ID);

ALTER TABLE TB_DESACR ADD CONSTRAINT fk_desacr_descontosacrescimos
FOREIGN KEY (DLO_DACID) REFERENCES TB_DESCONTOS_ACRESCIMOS(DAC_ID);

ALTER TABLE TB_LOCACOES_PAG ADD CONSTRAINT fk_locacoespagas_locacoes
FOREIGN KEY (LPA_LOCID) REFERENCES TB_LOCACOES(LOC_ID);
